version: '3'

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.66.0.0/16'

services:
  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: my_mysql
    volumes:
      - ./project/mydir:/mydir
      - ./project/datadir:/var/lib/mysql
      - ./project/conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./project/docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=upms"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
    networks:
      network:
        ipv4_address: 177.66.0.9
  redis:
    restart: always
    image: redis:6.0.9
    container_name: redis
    ports:
      - 6379:6379
    networks:
      network:
        ipv4_address: 177.66.0.10
  etcd1:
    restart: always
    image: quay.io/coreos/etcd:latest
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd1' # 节点名称
      - '--data-dir=/etcd_data' # 数据存储目录
      - '--initial-advertise-peer-urls=http://etcd1:2380' # 通知其他节点与本节点进行数据交换（选举，同步）的地址
      - '--listen-peer-urls=http://0.0.0.0:2380' # 本节点与其他节点进行数据交换(选举，数据同步)的监听地址
      - '--listen-client-urls=http://0.0.0.0:2379' # 本节点访问地址
      - '--advertise-client-urls=http://etcd1:2379' # 用于通知其他ETCD节点，客户端接入本节点的监听地址
      - '--initial-cluster-token=mys1cr2tt1k7n' # 集群唯一标识，相同标识的节点将视为在一个集群内
      - '--heartbeat-interval=250' # 客户端连接后的心跳间隔
      - '--election-timeout=1250' # 集群选举的超时时间
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380' # 集群所有节点配置
      - '--initial-cluster-state=new' # 节点初始化方式，new 表示如果没有集群不存在，创建新集群，existing表示如果集群不存在，节点将处于加入集群失败状态
    ports:
      - 23791:2379 # etcd目前默认使用2379端口提供HTTP API服务，2380端口和peer通信
    volumes:
      - ./project/etcd1/data:/etcd_data
    networks:
      network:
        ipv4_address: 177.66.0.11
  etcd2:
    restart: always
    image: quay.io/coreos/etcd:latest
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd2'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd2:2379'
      - '--initial-cluster-token=mys1cr2tt1k7n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 23792:2379
    volumes:
      - ./project/etcd2/data:/etcd_data
    networks:
      network:
        ipv4_address: 177.66.0.12
  etcd3:
    restart: always
    image: quay.io/coreos/etcd:latest
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd3'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://etcd3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd3:2379'
      - '--initial-cluster-token=mys1cr2tt1k7n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 23793:2379
    volumes:
      - ./project/etcd3/data:/etcd_data
    networks:
      network:
        ipv4_address: 177.66.0.13